server:
  port: 8088

spring:
  liquibase:
    enabled: false
  jpa:
    generate-ddl: true
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    database: postgresql
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    password: password
    username: root
    url: jdbc:postgresql://localhost:5432/security